# Generated by Django 3.2.23 on 2024-03-09 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_remove_order_main_number'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='KidsProduct',
            new_name='UnisexProduct',
        ),
        migrations.AlterField(
            model_name='product',
            name='product_for',
            field=models.CharField(blank=True, choices=[('Men', 'Men'), ('Woman', 'Woman'), ('unisex', 'unisex'), ('Animals', 'Animals'), ('Accessories', 'Accessories'), ('Others', 'Others')], default='', max_length=50, null=True),
        ),
    ]
