# Generated by Django 3.2.23 on 2024-03-09 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20240309_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='old_price',
            field=models.IntegerField(default='0'),
        ),
    ]
