# Generated by Django 3.2.23 on 2024-01-29 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_alter_order_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='main_number',
            field=models.CharField(default='sdlskdhgl', max_length=11),
        ),
    ]
