# Generated by Django 3.2.23 on 2024-01-29 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_order_main_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='main_number',
        ),
    ]
