# Generated by Django 3.2.23 on 2024-01-07 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('carousel_number', models.IntegerField(default='0')),
                ('image_class', models.TextField(default='If carousel number = 1 then image class = image_first and css_class = first', max_length=180)),
                ('title', models.TextField(blank=True, max_length=500, null=True)),
                ('description', models.TextField(blank=True, max_length=10000, null=True)),
                ('extra_info', models.TextField(blank=True, max_length=1000, null=True)),
                ('btn_main_first', models.TextField(blank=True, default='Important : use this button for 1st carousel image only', max_length=200, null=True)),
                ('btn_sub_first', models.TextField(blank=True, default='Important : use this button for 1st carousel image only', max_length=200, null=True)),
                ('btn_main_second', models.TextField(blank=True, default='Important : use this button for 2nd carousel image only', max_length=200, null=True)),
                ('btn_sub_second', models.TextField(blank=True, default='Important : use this button for 2nd carousel image only', max_length=200, null=True)),
                ('btn_main_third', models.TextField(blank=True, default='Important : use this button for 3th carousel image only', max_length=200, null=True)),
                ('btn_sub_third', models.TextField(blank=True, default='Important : use this button for 3th carousel image only', max_length=200, null=True)),
                ('btn_main_fourth', models.TextField(blank=True, default='Important : use this button for 4th carousel image only', max_length=200, null=True)),
                ('btn_sub_fourth', models.TextField(blank=True, default='Important : use this button for 4th carousel image only', max_length=200, null=True)),
                ('css_class', models.TextField(max_length=50)),
            ],
            options={
                'ordering': ['carousel_number'],
            },
        ),
        migrations.CreateModel(
            name='InfoCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('css_class', models.CharField(blank=True, max_length=50, null=True)),
                ('title', models.TextField(blank=True, max_length=500, null=True)),
                ('description_first', models.TextField(blank=True, max_length=10000, null=True)),
                ('description_second', models.TextField(blank=True, max_length=10000, null=True)),
            ],
            options={
                'verbose_name_plural': '1st Section below Carousel on Homepage',
            },
        ),
        migrations.CreateModel(
            name='IntroCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('css_class', models.CharField(blank=True, max_length=50, null=True)),
                ('title', models.TextField(blank=True, max_length=500, null=True)),
                ('description', models.TextField(blank=True, max_length=10000, null=True)),
            ],
            options={
                'verbose_name_plural': '2nd Section below Carousel on Homepage',
            },
        ),
        migrations.CreateModel(
            name='OfferText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_title1', models.TextField(blank=True, max_length=200, null=True)),
                ('offer_title2', models.TextField(blank=True, max_length=200, null=True)),
                ('offer_title3', models.TextField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': 'Offer Text',
            },
        ),
    ]
