# Generated by Django 3.2.23 on 2024-01-11 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_carousel_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('heading', models.TextField(blank=True, max_length=500, null=True)),
                ('description', models.TextField(blank=True, max_length=10000, null=True)),
                ('btn_card', models.TextField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'Card',
            },
        ),
        migrations.DeleteModel(
            name='InfoCard',
        ),
        migrations.DeleteModel(
            name='IntroCard',
        ),
        migrations.RemoveField(
            model_name='carousel',
            name='btn_main_fourth',
        ),
        migrations.RemoveField(
            model_name='carousel',
            name='btn_sub_fourth',
        ),
    ]
