# Generated by Django 3.2.23 on 2024-01-11 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20240111_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='cards',
            name='title',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
