# Generated by Django 3.2.23 on 2024-01-17 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_cards_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextOnHomepage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, max_length=500, null=True)),
                ('heading', models.TextField(blank=True, max_length=500, null=True)),
                ('description', models.TextField(blank=True, max_length=10000, null=True)),
                ('btn_text', models.TextField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
