# Generated by Django 3.2.23 on 2024-01-19 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_textonhomepage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='textonhomepage',
            options={'verbose_name_plural': 'Text below Carousel'},
        ),
    ]
