# Generated by Django 3.2.23 on 2024-02-05 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_textonhomepage_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='First Name', max_length=250)),
                ('last_name', models.CharField(default='Last Name', max_length=250)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField(max_length=1000)),
            ],
            options={
                'verbose_name_plural': 'Contact',
            },
        ),
    ]
