# Generated by Django 3.2.23 on 2024-02-06 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
