# Generated by Django 3.2.23 on 2024-03-12 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='discount_amount',
            field=models.FloatField(),
        ),
    ]
